name: Monitor service docker build

on:
  push:
    paths:
      - 'monitor/**'
      - '!.github/**'
      - '!*.md'
  workflow_dispatch:

jobs:
  build-and-push-image:
    uses: ./.github/workflows/dockerhub-callable.yaml
    secrets: inherit
    with:
      multiarch: false # whisper.cpp fails to compile on arm
      image: 'hx-monitor-service'
      dockerfile: 'monitor/Dockerfile'
      context: ./monitor