name: Monitor service docker build

on:
  push:
    paths:
      - '.'
      - '!frontend/**'
      - '!.github/**'
      - '!api-backend/**'
      - '!*.txt'
      - '!*.md'
      - '!.gitignore'
      - '!tests/**'
  workflow_dispatch:

jobs:
  build-and-push-image:
    uses: ./.github/workflows/dockerhub-callable.yaml
    secrets: inherit
    with:
      image: 'hx-monitor-service'
      context: .