name: Monitor API backend docker build

on:
  push:
    paths:
      - 'api-backend/**'
      - '!*.md'

jobs:
  build-and-push-image:
    - uses: actions/checkout@v4
    - uses: ./.github/workflows/dockerhub-callable.yaml
      with:
        image: 'hx-monitor-backend'
        context: .
      secrets:
        DOCKER_HUB_SECRET: ${{ secrets.DOCKER_HUB_SECRET }}