name: Monitor API backend docker build

on:
  push:
    paths:
      - 'api-backend/**'
      - '!.github/**'
      - '!*.md'

jobs:
  build-and-push-image:
    uses: ./.github/workflows/dockerhub-callable.yaml
    secrets: inherit
    with:
      image: 'hx-monitor-api-backend'
      context: .