name: Monitor API backend docker build

on:
  push:
    paths:
      - 'api-backend/**'
      - '!*.md'

jobs:
  build-and-push-image:
    uses: .github/workflows/dockerhub-callable.yaml
    with:
      image: 'hx-monitor-api'
      context: ./api-backend
    secrets:
      DOCKER_HUB_SECRET: ${{ secrets.DOCKER_HUB_SECRET }}