name: Monitor service docker build

on:
  push:
    paths:
      - '!frontend/**'
      - '!api-backend/**'
      - '!*.txt'
      - '!*.md'
      - '!.gitignore'
      - '!tests/**'

jobs:
  build-and-push-image:
    uses: ./.github/workflows/dockerhub-callable.yml
    with:
      image: 'hx-monitor-service'
    secrets:
      DOCKER_HUB_SECRET: ${{ secrets.DOCKER_HUB_SECRET }}