name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      image:
        description: 'Docker image name'
        required: true
        type: string
      context:
        description: 'Build context'
        default: '.'
        required: false
        type: string
      dockerfile:
        default: 'Dockerfile'
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Docker login
      uses: docker/login-action@v3
      with:
        username: thisisnttheway
        password: ${{ secrets.DOCKER_HUB_SECRET }}
    
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: thisisnttheway/${{ inputs.image }}
        tags: |
          type=semver,pattern={{version}}
          type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
          type=ref,event=branch,enable=${{ github.ref != format('refs/heads/{0}', 'main') }}
      
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
