name: Frontend

on:
  push:
    paths:
      - 'frontend/**'
      - '!frontend/*.py'
      - '!frontend/*.json'
      - '!frontend/*ocker*'
      - '!frontend/*.md'
      - '!frontend/public/**'

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Cache node_modules
      uses: actions/cache@v4
      with:
        path: "frontend/node_modules"
        key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
        restore-keys: ${{ runner.os }}-modules-

    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
          node-version-file: "frontend/.nvmrc"
    - name: Install modules
      run: npm install
      working-directory: frontend
    - name: ESlint
      run: npx eslint .
      working-directory: frontend
    #- name: Build
    #  run: npm run build
    #  working-directory: frontend